import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import IndikatorAndroid from '@/components/indikator'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative bg-primary w-[375px] h-[812px] rounded-xl bg-gradient-radial-tr from-gradient-start to-gradient-end">
          <IndikatorAndroid />
          <main className='h-full'>
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
